name: "Terraform / Terragrunt CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: "Validate Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: "1.8.2"

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@6fb92a5002c17d0e7d3327b4022569eb865f3148 # v3.0.0
        with:
          terragrunt-version: "0.58.0"

      - name: Setup Terragrunt Provider Cache
        run: |
          mkdir -p ${{ github.workspace }}/.cache/terragrunt/providers
          echo "TERRAGRUNT_PROVIDER_CACHE=1" >> $GITHUB_ENV
          echo "TERRAGRUNT_PROVIDER_CACHE_DIR=${{ github.workspace }}/.cache/terragrunt/providers" >> $GITHUB_ENV

      - name: Cache Terraform Plugins
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ github.workspace }}/.cache/terragrunt/providers
          key: terraform-plugin-cache-${{ runner.os }}-${{ hashFiles('terragrunt.hcl') }}
          restore-keys: |
            terraform-plugin-cache-${{ runner.os }}-

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terragrunt Validate
        run: terragrunt run-all validate
        env:
          TF_VAR_proxmox_endpoint: "https://localhost:8006/"
          TF_VAR_proxmox_api_token: "dummy-token-for-validation"
